
package com.jsako.crmbos.service.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.jsako.crmbos.service.Customer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.crmbos.jsako.com/")
@XmlSeeAlso({
})
public interface ICustomerService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "clearDecidedzoneByDecidedzoneId", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.ClearDecidedzoneByDecidedzoneId")
    @ResponseWrapper(localName = "clearDecidedzoneByDecidedzoneIdResponse", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.ClearDecidedzoneByDecidedzoneIdResponse")
    public void clearDecidedzoneByDecidedzoneId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.jsako.crmbos.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListByDecidedzoneId", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.FindListByDecidedzoneId")
    @ResponseWrapper(localName = "findListByDecidedzoneIdResponse", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.FindListByDecidedzoneIdResponse")
    public List<Customer> findListByDecidedzoneId(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.jsako.crmbos.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.FindAllResponse")
    public List<Customer> findAll();

    /**
     * 
     * @return
     *     returns java.util.List<com.jsako.crmbos.service.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListNotAssociation", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.FindListNotAssociation")
    @ResponseWrapper(localName = "findListNotAssociationResponse", targetNamespace = "http://service.crmbos.jsako.com/", className = "com.jsako.crmbos.service.FindListNotAssociationResponse")
    public List<Customer> findListNotAssociation();

}
